name: 报告bug
description: |
  上报有关应用的错误和异常等。
  安全漏洞类的bug（例如账号cookie泄露）不要在此上报，请论坛私信联系@ruik0
title: "[BUG] "
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        感谢您上报问题，**请在上方标题栏填写清晰的问题摘要，包含问题发生的位置和现象**。
        > 例如：`[BUG] 帖子页面内回复时应用闪退`、`[BUG] 设置中更改主题颜色后没有效果`
  - type: checkboxes
    attributes:
      label: |
        确认事项
      description: |
        在提交issue前确认以下事项，否则issue可能会被关闭。
      options:
        - label: |
            我已确认网页端论坛的相应页面（如果有）不存在相应的错误行为，这个问题只存在于客户端。
          required: true
        - label: |
            我已在[最新稳定版](https://github.com/realth000/tsdm_client/releases/latest)上验证，该问题依然存在。
          required: true
        - label: |
            我已在[issue](https://github.com/realth000/tsdm_client/issues?q=sort%3Aupdated-desc%20is%3Aissue)中搜索，确认没有重复或类似issue。
          required: true
        - label: |
            我已确认这个问题不属于[已知问题](https://github.com/realth000/tsdm_client#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98)
          required: true
        - label: |
            我确认这个问题不属于安全漏洞（例如账号cookie超时、泄露）。
          required: true
  - type: textarea
    attributes:
      label: |
        复现步骤
      description: |
        复现问题的步骤，在什么情况下按照什么样的步骤进行操作会出现问题。
      placeholder: |
        1. ...
        2. ...
        3. ...
      validations:
        required: true
  - type: textarea
    attributes:
      label: |
        预期的结果
      description: |
        按照复现步骤操作后，预期出现的现象或结果
      validations:
        required: true
  - type: textarea
    attributes:
      label: |
        预期的结果
      description: |
        按照复现步骤操作后，实际出现的现象或结果
      validations:
        required: true
  - type: textarea
    attributes:
      label: |
        附加信息
      description: |
        任何有助于描述问题、帮助开发者定位问题的现象、信息都可以放在这里。
        
        * 如果上传截图或视频，请简练地给出涉及问题的部分。
        * 如果问题不会使软件退出，请重启app，复现一次问题，而后在`设置 -> 调试 -> 日志 -> 右上角菜单`中点击“Copy all logs” 后粘贴日志。
        * 如果问题会导致软件退出，请于复现问题在`设置 -> 调试 -> 查看历史日志`中选择发生问题的日期，右上角导出日志后将日志作为附件上传。
      value: |
        <details>
        <summary>截图或视频</summary>


        在此粘贴截图


        </details>

        <details><summary>当次启动日志</summary>


        ```console
        在此粘贴日志
        ```


        </details>
      validations:
        required: false