import 'package:collection/collection.dart';
import 'package:dart_mappable/dart_mappable.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:tsdm_client/extensions/string.dart';
import 'package:tsdm_client/extensions/universal_html.dart';
import 'package:tsdm_client/utils/css_parser.dart';
import 'package:tsdm_client/utils/debug.dart';
import 'package:universal_html/html.dart' as uh;

part '../../generated/shared/models/models.mapper.dart';
part 'css_types.dart';
part 'emoji.dart';
part 'forum.dart';
part 'forum_group.dart';
part 'locked.dart';
part 'normal_thread.dart';
part 'post.dart';
part 'rate.dart';
part 'reply_parameters.dart';
part 'stick_thread.dart';
part 'thread_type.dart';
part 'user.dart';
