import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    cookie,
    imageCache,
    settings,
    threadVisitHistory,
  ];
  late final Shape0 cookie = Shape0(
      source: i0.VersionedTable(
        entityName: 'cookie',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 imageCache = Shape1(
      source: i0.VersionedTable(
        entityName: 'image_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(url)',
        ],
        columns: [
          _column_4,
          _column_5,
          _column_6,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 settings = Shape2(
      source: i0.VersionedTable(
        entityName: 'settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(name)',
        ],
        columns: [
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 threadVisitHistory = Shape3(
      source: i0.VersionedTable(
        entityName: 'thread_visit_history',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, tid)',
        ],
        columns: [
          _column_1,
          _column_14,
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cookie =>
      columnsByName['cookie']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('username', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>('uid', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('cookie', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastCachedTime =>
      columnsByName['last_cached_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastUsedTime =>
      columnsByName['last_used_time']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('file_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_6(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_cached_time', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_7(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_used_time', aliasedName, false,
        type: i1.DriftSqlType.dateTime);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intValue =>
      columnsByName['int_value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get doubleValue =>
      columnsByName['double_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get stringValue =>
      columnsByName['string_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get boolValue =>
      columnsByName['bool_value']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get dateTimeValue =>
      columnsByName['date_time_value']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('int_value', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>('double_value', aliasedName, true,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('string_value', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_12(String aliasedName) =>
    i1.GeneratedColumn<bool>('bool_value', aliasedName, true,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("bool_value" IN (0, 1))'));
i1.GeneratedColumn<DateTime> _column_13(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('date_time_value', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tid =>
      columnsByName['tid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get threadTitle =>
      columnsByName['thread_title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fid =>
      columnsByName['fid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get forumName =>
      columnsByName['forum_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get visitTime =>
      columnsByName['visit_time']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>('tid', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('thread_title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>('fid', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>('forum_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_18(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('visit_time', aliasedName, false,
        type: i1.DriftSqlType.dateTime);

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    cookie,
    imageCache,
    settings,
    threadVisitHistory,
  ];
  late final Shape4 cookie = Shape4(
      source: i0.VersionedTable(
        entityName: 'cookie',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_19,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 imageCache = Shape1(
      source: i0.VersionedTable(
        entityName: 'image_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(url)',
        ],
        columns: [
          _column_4,
          _column_5,
          _column_6,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 settings = Shape5(
      source: i0.VersionedTable(
        entityName: 'settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(name)',
        ],
        columns: [
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 threadVisitHistory = Shape3(
      source: i0.VersionedTable(
        entityName: 'thread_visit_history',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, tid)',
        ],
        columns: [
          _column_1,
          _column_14,
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cookie =>
      columnsByName['cookie']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastCheckin =>
      columnsByName['last_checkin']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<DateTime> _column_19(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_checkin', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intValue =>
      columnsByName['int_value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get doubleValue =>
      columnsByName['double_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get stringValue =>
      columnsByName['string_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get boolValue =>
      columnsByName['bool_value']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get dateTimeValue =>
      columnsByName['date_time_value']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get sizeValue =>
      columnsByName['size_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get offsetValue =>
      columnsByName['offset_value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>('size_value', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('offset_value', aliasedName, true,
        type: i1.DriftSqlType.string);

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    broadcastMessage,
    cookie,
    imageCache,
    notice,
    personalMessage,
    settings,
    threadVisitHistory,
    userAvatar,
  ];
  late final Shape6 broadcastMessage = Shape6(
      source: i0.VersionedTable(
        entityName: 'broadcast_message',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, timestamp)',
        ],
        columns: [
          _column_1,
          _column_22,
          _column_23,
          _column_24,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 cookie = Shape7(
      source: i0.VersionedTable(
        entityName: 'cookie',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_3,
          _column_19,
          _column_25,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 imageCache = Shape8(
      source: i0.VersionedTable(
        entityName: 'image_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(url)',
        ],
        columns: [
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 notice = Shape9(
      source: i0.VersionedTable(
        entityName: 'notice',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, timestamp)',
        ],
        columns: [
          _column_1,
          _column_27,
          _column_22,
          _column_23,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 personalMessage = Shape10(
      source: i0.VersionedTable(
        entityName: 'personal_message',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, timestamp)',
        ],
        columns: [
          _column_1,
          _column_22,
          _column_23,
          _column_28,
          _column_29,
          _column_30,
          _column_31,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 settings = Shape5(
      source: i0.VersionedTable(
        entityName: 'settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(name)',
        ],
        columns: [
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 threadVisitHistory = Shape3(
      source: i0.VersionedTable(
        entityName: 'thread_visit_history',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, tid)',
        ],
        columns: [
          _column_1,
          _column_14,
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 userAvatar = Shape11(
      source: i0.VersionedTable(
        entityName: 'user_avatar',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(username)',
        ],
        columns: [
          _column_0,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pmid =>
      columnsByName['pmid']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('timestamp', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('data', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>('pmid', aliasedName, false,
        type: i1.DriftSqlType.int);

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cookie =>
      columnsByName['cookie']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastCheckin =>
      columnsByName['last_checkin']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastFetchNotice =>
      columnsByName['last_fetch_notice']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<DateTime> _column_25(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_fetch_notice', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastCachedTime =>
      columnsByName['last_cached_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastUsedTime =>
      columnsByName['last_used_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get usage =>
      columnsByName['usage']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>('usage', aliasedName, true,
        type: i1.DriftSqlType.int);

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nid =>
      columnsByName['nid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>('nid', aliasedName, false,
        type: i1.DriftSqlType.int);

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get peerUid =>
      columnsByName['peer_uid']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get peerUsername =>
      columnsByName['peer_username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get sender =>
      columnsByName['sender']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get alreadyRead =>
      columnsByName['already_read']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>('peer_uid', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('peer_username', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_30(String aliasedName) =>
    i1.GeneratedColumn<bool>('sender', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("sender" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_31(String aliasedName) =>
    i1.GeneratedColumn<bool>('already_read', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("already_read" IN (0, 1))'));

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cacheName =>
      columnsByName['cache_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>('cache_name', aliasedName, false,
        type: i1.DriftSqlType.string);

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    broadcastMessage,
    cookie,
    imageCache,
    notice,
    personalMessage,
    settings,
    threadVisitHistory,
    userAvatar,
  ];
  late final Shape6 broadcastMessage = Shape6(
      source: i0.VersionedTable(
        entityName: 'broadcast_message',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, timestamp)',
        ],
        columns: [
          _column_1,
          _column_22,
          _column_23,
          _column_24,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 cookie = Shape7(
      source: i0.VersionedTable(
        entityName: 'cookie',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_3,
          _column_19,
          _column_25,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 imageCache = Shape8(
      source: i0.VersionedTable(
        entityName: 'image_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(url)',
        ],
        columns: [
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 notice = Shape9(
      source: i0.VersionedTable(
        entityName: 'notice',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, nid)',
        ],
        columns: [
          _column_1,
          _column_27,
          _column_22,
          _column_23,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 personalMessage = Shape10(
      source: i0.VersionedTable(
        entityName: 'personal_message',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, timestamp)',
        ],
        columns: [
          _column_1,
          _column_22,
          _column_23,
          _column_28,
          _column_29,
          _column_30,
          _column_31,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 settings = Shape5(
      source: i0.VersionedTable(
        entityName: 'settings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(name)',
        ],
        columns: [
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_20,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 threadVisitHistory = Shape3(
      source: i0.VersionedTable(
        entityName: 'thread_visit_history',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(uid, tid)',
        ],
        columns: [
          _column_1,
          _column_14,
          _column_0,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 userAvatar = Shape11(
      source: i0.VersionedTable(
        entityName: 'user_avatar',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(username)',
        ],
        columns: [
          _column_0,
          _column_32,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
      from4To5: from4To5,
    ));
