import 'dart:ui';

// All colors in current file are defined in web standards.
// ignore_for_file: public_member_api_docs

enum WebColors {
  aliceBlue(Color(0xFFF0F8FF)),
  antiqueWhite(Color(0xFFFAEBD7)),
  aqua(Color(0xFF00FFFF)),
  aquamarine(Color(0xFF7FFFD4)),
  azure(Color(0xFFF0FFFF)),
  beige(Color(0xFFF5F5DC)),
  bisque(Color(0xFFFFE4C4)),
  black(Color(0xFF000000)),
  blanchedAlmond(Color(0xFFFFEBCD)),
  blue(Color(0xFF0000FF)),
  blueViolet(Color(0xFF8A2BE2)),
  brown(Color(0xFFA52A2A)),
  burlyWood(Color(0xFFDEB887)),
  cadetBlue(Color(0xFF5F9EA0)),
  chartreuse(Color(0xFF7FFF00)),
  chocolate(Color(0xFFD2691E)),
  coral(Color(0xFFFF7F50)),
  cornflowerBlue(Color(0xFF6495ED)),
  cornsilk(Color(0xFFFFF8DC)),
  crimson(Color(0xFFDC143C)),
  cyan(Color(0xFF00FFFF)),
  darkBlue(Color(0xFF00008B)),
  darkCyan(Color(0xFF008B8B)),
  darkGoldenRod(Color(0xFFB8860B)),
  darkGray(Color(0xFFA9A9A9)),
  darkGrey(Color(0xFFA9A9A9)),
  darkGreen(Color(0xFF006400)),
  darkKhaki(Color(0xFFBDB76B)),
  darkMagenta(Color(0xFF8B008B)),
  darkOliveGreen(Color(0xFF556B2F)),
  darkOrange(Color(0xFFFF8C00)),
  darkOrchid(Color(0xFF9932CC)),
  darkRed(Color(0xFF8B0000)),
  darkSalmon(Color(0xFFE9967A)),
  darkSeaGreen(Color(0xFF8FBC8F)),
  darkSlateBlue(Color(0xFF483D8B)),
  darkSlateGray(Color(0xFF2F4F4F)),
  darkSlateGrey(Color(0xFF2F4F4F)),
  darkTurquoise(Color(0xFF00CED1)),
  darkViolet(Color(0xFF9400D3)),
  deepPink(Color(0xFFFF1493)),
  deepSkyBlue(Color(0xFF00BFFF)),
  dimGray(Color(0xFF696969)),
  dimGrey(Color(0xFF696969)),
  dodgerBlue(Color(0xFF1E90FF)),
  fireBrick(Color(0xFFB22222)),
  floralWhite(Color(0xFFFFFAF0)),
  forestGreen(Color(0xFF228B22)),
  fuchsia(Color(0xFFFF00FF)),
  gainsboro(Color(0xFFDCDCDC)),
  ghostWhite(Color(0xFFF8F8FF)),
  gold(Color(0xFFFFD700)),
  goldenRod(Color(0xFFDAA520)),
  gray(Color(0xFF808080)),
  grey(Color(0xFF808080)),
  green(Color(0xFF008000)),
  greenYellow(Color(0xFFADFF2F)),
  honeyDew(Color(0xFFF0FFF0)),
  hotPink(Color(0xFFFF69B4)),
  indianRed(Color(0xFFCD5C5C)),
  indigo(Color(0xFF4B0082)),
  ivory(Color(0xFFFFFFF0)),
  khaki(Color(0xFFF0E68C)),
  lavender(Color(0xFFE6E6FA)),
  lavenderBlush(Color(0xFFFFF0F5)),
  lawnGreen(Color(0xFF7CFC00)),
  lemonChiffon(Color(0xFFFFFACD)),
  lightBlue(Color(0xFFADD8E6)),
  lightCoral(Color(0xFFF08080)),
  lightCyan(Color(0xFFE0FFFF)),
  lightGoldenRodYellow(Color(0xFFFAFAD2)),
  lightGray(Color(0xFFD3D3D3)),
  lightGrey(Color(0xFFD3D3D3)),
  lightGreen(Color(0xFF90EE90)),
  lightPink(Color(0xFFFFB6C1)),
  lightSalmon(Color(0xFFFFA07A)),
  lightSeaGreen(Color(0xFF20B2AA)),
  lightSkyBlue(Color(0xFF87CEFA)),
  lightSlateGray(Color(0xFF778899)),
  lightSlateGrey(Color(0xFF778899)),
  lightSteelBlue(Color(0xFFB0C4DE)),
  lightYellow(Color(0xFFFFFFE0)),
  lime(Color(0xFF00FF00)),
  limeGreen(Color(0xFF32CD32)),
  linen(Color(0xFFFAF0E6)),
  magenta(Color(0xFFFF00FF)),
  maroon(Color(0xFF800000)),
  mediumAquaMarine(Color(0xFF66CDAA)),
  mediumBlue(Color(0xFF0000CD)),
  mediumOrchid(Color(0xFFBA55D3)),
  mediumPurple(Color(0xFF9370DB)),
  mediumSeaGreen(Color(0xFF3CB371)),
  mediumSlateBlue(Color(0xFF7B68EE)),
  mediumSpringGreen(Color(0xFF00FA9A)),
  mediumTurquoise(Color(0xFF48D1CC)),
  mediumVioletRed(Color(0xFFC71585)),
  midnightBlue(Color(0xFF191970)),
  mintCream(Color(0xFFF5FFFA)),
  mistyRose(Color(0xFFFFE4E1)),
  moccasin(Color(0xFFFFE4B5)),
  navajoWhite(Color(0xFFFFDEAD)),
  navy(Color(0xFF000080)),
  oldLace(Color(0xFFFDF5E6)),
  olive(Color(0xFF808000)),
  oliveDrab(Color(0xFF6B8E23)),
  orange(Color(0xFFFFA500)),
  orangeRed(Color(0xFFFF4500)),
  orchid(Color(0xFFDA70D6)),
  paleGoldenRod(Color(0xFFEEE8AA)),
  paleGreen(Color(0xFF98FB98)),
  paleTurquoise(Color(0xFFAFEEEE)),
  paleVioletRed(Color(0xFFDB7093)),
  papayaWhip(Color(0xFFFFEFD5)),
  peachPuff(Color(0xFFFFDAB9)),
  peru(Color(0xFFCD853F)),
  pink(Color(0xFFFFC0CB)),
  plum(Color(0xFFDDA0DD)),
  powderBlue(Color(0xFFB0E0E6)),
  purple(Color(0xFF800080)),
  rebeccaPurple(Color(0xFF663399)),
  red(Color(0xFFFF0000)),
  rosyBrown(Color(0xFFBC8F8F)),
  royalBlue(Color(0xFF4169E1)),
  saddleBrown(Color(0xFF8B4513)),
  salmon(Color(0xFFFA8072)),
  sandyBrown(Color(0xFFF4A460)),
  seaGreen(Color(0xFF2E8B57)),
  seaShell(Color(0xFFFFF5EE)),
  sienna(Color(0xFFA0522D)),
  silver(Color(0xFFC0C0C0)),
  skyBlue(Color(0xFF87CEEB)),
  slateBlue(Color(0xFF6A5ACD)),
  slateGray(Color(0xFF708090)),
  slateGrey(Color(0xFF708090)),
  snow(Color(0xFFFFFAFA)),
  springGreen(Color(0xFF00FF7F)),
  steelBlue(Color(0xFF4682B4)),
  tan(Color(0xFFD2B48C)),
  teal(Color(0xFF008080)),
  thistle(Color(0xFFD8BFD8)),
  tomato(Color(0xFFFF6347)),
  turquoise(Color(0xFF40E0D0)),
  violet(Color(0xFFEE82EE)),
  wheat(Color(0xFFF5DEB3)),
  white(Color(0xFFFFFFFF)),
  whiteSmoke(Color(0xFFF5F5F5)),
  yellow(Color(0xFFFFFF00)),
  yellowGreen(Color(0xFF9ACD32)),
  invalid(Color(0x00000000));

  const WebColors(this.color);

  factory WebColors.fromString(String? c) {
    return switch (c?.toLowerCase()) {
      'aliceblue' => WebColors.aliceBlue,
      'antiquewhite' => WebColors.antiqueWhite,
      'aqua' => WebColors.aqua,
      'aquamarine' => WebColors.aquamarine,
      'azure' => WebColors.azure,
      'beige' => WebColors.beige,
      'bisque' => WebColors.bisque,
      'black' => WebColors.black,
      'blanchedalmond' => WebColors.blanchedAlmond,
      'blue' => WebColors.blue,
      'blueviolet' => WebColors.blueViolet,
      'brown' => WebColors.brown,
      'burlywood' => WebColors.burlyWood,
      'cadetblue' => WebColors.cadetBlue,
      'chartreuse' => WebColors.chartreuse,
      'chocolate' => WebColors.chocolate,
      'coral' => WebColors.coral,
      'cornflowerblue' => WebColors.cornflowerBlue,
      'cornsilk' => WebColors.cornsilk,
      'crimson' => WebColors.crimson,
      'cyan' => WebColors.cyan,
      'darkblue' => WebColors.darkBlue,
      'darkcyan' => WebColors.darkCyan,
      'darkgoldenrod' => WebColors.darkGoldenRod,
      'darkgray' => WebColors.darkGray,
      'darkgrey' => WebColors.darkGrey,
      'darkgreen' => WebColors.darkGreen,
      'darkkhaki' => WebColors.darkKhaki,
      'darkmagenta' => WebColors.darkMagenta,
      'darkolivegreen' => WebColors.darkOliveGreen,
      'darkorange' => WebColors.darkOrange,
      'darkorchid' => WebColors.darkOrchid,
      'darkred' => WebColors.darkRed,
      'darksalmon' => WebColors.darkSalmon,
      'darkseagreen' => WebColors.darkSeaGreen,
      'darkslateblue' => WebColors.darkSlateBlue,
      'darkslategray' => WebColors.darkSlateGray,
      'darkslategrey' => WebColors.darkSlateGrey,
      'darkturquoise' => WebColors.darkTurquoise,
      'darkviolet' => WebColors.darkViolet,
      'deeppink' => WebColors.deepPink,
      'deepskyblue' => WebColors.deepSkyBlue,
      'dimgray' => WebColors.dimGray,
      'dimgrey' => WebColors.dimGrey,
      'dodgerblue' => WebColors.dodgerBlue,
      'firebrick' => WebColors.fireBrick,
      'floralwhite' => WebColors.floralWhite,
      'forestgreen' => WebColors.forestGreen,
      'fuchsia' => WebColors.fuchsia,
      'gainsboro' => WebColors.gainsboro,
      'ghostwhite' => WebColors.ghostWhite,
      'gold' => WebColors.gold,
      'goldenrod' => WebColors.goldenRod,
      'gray' => WebColors.gray,
      'grey' => WebColors.grey,
      'green' => WebColors.green,
      'greenyellow' => WebColors.greenYellow,
      'honeydew' => WebColors.honeyDew,
      'hotpink' => WebColors.hotPink,
      'indianred' => WebColors.indianRed,
      'indigo' => WebColors.indigo,
      'ivory' => WebColors.ivory,
      'khaki' => WebColors.khaki,
      'lavender' => WebColors.lavender,
      'lavenderblush' => WebColors.lavenderBlush,
      'lawngreen' => WebColors.lawnGreen,
      'lemonchiffon' => WebColors.lemonChiffon,
      'lightblue' => WebColors.lightBlue,
      'lightcoral' => WebColors.lightCoral,
      'lightcyan' => WebColors.lightCyan,
      'lightgoldenrodyellow' => WebColors.lightGoldenRodYellow,
      'lightgray' => WebColors.lightGray,
      'lightgrey' => WebColors.lightGrey,
      'lightgreen' => WebColors.lightGreen,
      'lightpink' => WebColors.lightPink,
      'lightsalmon' => WebColors.lightSalmon,
      'lightseagreen' => WebColors.lightSeaGreen,
      'lightskyblue' => WebColors.lightSkyBlue,
      'lightslategray' => WebColors.lightSlateGray,
      'lightslategrey' => WebColors.lightSlateGrey,
      'lightsteelblue' => WebColors.lightSteelBlue,
      'lightyellow' => WebColors.lightYellow,
      'lime' => WebColors.lime,
      'limegreen' => WebColors.limeGreen,
      'linen' => WebColors.linen,
      'magenta' => WebColors.magenta,
      'maroon' => WebColors.maroon,
      'mediumaquamarine' => WebColors.mediumAquaMarine,
      'mediumblue' => WebColors.mediumBlue,
      'mediumorchid' => WebColors.mediumOrchid,
      'mediumpurple' => WebColors.mediumPurple,
      'mediumseagreen' => WebColors.mediumSeaGreen,
      'mediumslateblue' => WebColors.mediumSlateBlue,
      'mediumspringgreen' => WebColors.mediumSpringGreen,
      'mediumturquoise' => WebColors.mediumTurquoise,
      'mediumvioletred' => WebColors.mediumVioletRed,
      'midnightblue' => WebColors.midnightBlue,
      'mintcream' => WebColors.mintCream,
      'mistyrose' => WebColors.mistyRose,
      'moccasin' => WebColors.moccasin,
      'navajowhite' => WebColors.navajoWhite,
      'navy' => WebColors.navy,
      'oldlace' => WebColors.oldLace,
      'olive' => WebColors.olive,
      'olivedrab' => WebColors.oliveDrab,
      'orange' => WebColors.orange,
      'orangered' => WebColors.orangeRed,
      'orchid' => WebColors.orchid,
      'palegoldenrod' => WebColors.paleGoldenRod,
      'palegreen' => WebColors.paleGreen,
      'paleturquoise' => WebColors.paleTurquoise,
      'palevioletred' => WebColors.paleVioletRed,
      'papayawhip' => WebColors.papayaWhip,
      'peachpuff' => WebColors.peachPuff,
      'peru' => WebColors.peru,
      'pink' => WebColors.pink,
      'plum' => WebColors.plum,
      'powderblue' => WebColors.powderBlue,
      'purple' => WebColors.purple,
      'rebeccapurple' => WebColors.rebeccaPurple,
      'red' => WebColors.red,
      'rosybrown' => WebColors.rosyBrown,
      'royalblue' => WebColors.royalBlue,
      'saddlebrown' => WebColors.saddleBrown,
      'salmon' => WebColors.salmon,
      'sandybrown' => WebColors.sandyBrown,
      'seagreen' => WebColors.seaGreen,
      'seashell' => WebColors.seaShell,
      'sienna' => WebColors.sienna,
      'silver' => WebColors.silver,
      'skyblue' => WebColors.skyBlue,
      'slateblue' => WebColors.slateBlue,
      'slategray' => WebColors.slateGray,
      'slategrey' => WebColors.slateGrey,
      'snow' => WebColors.snow,
      'springgreen' => WebColors.springGreen,
      'steelblue' => WebColors.steelBlue,
      'tan' => WebColors.tan,
      'teal' => WebColors.teal,
      'thistle' => WebColors.thistle,
      'tomato' => WebColors.tomato,
      'turquoise' => WebColors.turquoise,
      'violet' => WebColors.violet,
      'wheat' => WebColors.wheat,
      'white' => WebColors.white,
      'whitesmoke' => WebColors.whiteSmoke,
      'yellow' => WebColors.yellow,
      'yellowgreen' => WebColors.yellowGreen,
      String() || null => WebColors.invalid,
    };
  }

  bool get isValid => this != WebColors.invalid;

  bool get isNotValid => !isValid;

  final Color color;
}
